### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#64]
![image](https://user-images.githubusercontent.com/1689183/51220843-c56ac200-18eb-11e9-9d9c-9c0528a1a672.png)

**Comment by hesyifei** [comment]
One great website I used in the past to generate favicon for different browsers/platforms: https://realfavicongenerator.net/

**Comment by hesyifei** [comment]
Since WordPress 4.3, we can set the site icon in "Customizing" -> "Site Identity" -> "Site Icon". We don't need to add favicon manually.

<img width="298" alt="screen shot 2019-01-31 at 11 37 15 pm" src="https://user-images.githubusercontent.com/4939421/52109130-3f1fd280-25b1-11e9-98e5-fa2bf5f2ae10.png">

**Comment by epicfaace** [comment]
Can you add this step in the wiki page for "todos before deploying"?
